<%@ Page Language="C#" AutoEventWireup="true" CodeFile="HandSetOfferTypeManagement.aspx.cs" Inherits="Web_HandSetOfferTypeManagement" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <asp:GridView ID="HandSetOfferTypeGw" runat="server" DataKeyNames="Index" DataSourceID="HandSetOfferTypeObj"
 AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
AutoGenerateColumns="false"  >
<Columns>
<asp:TemplateField Visible="false">
<ItemTemplate>
<asp:Literal ID="Index" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"Index") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="Index" runat="server" Text='<%# Bind(Container.DataItem,"Index") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="Index" runat="server" Text='<%# Bind(Container.DataItem,"Index") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
<asp:TemplateField Visible="true">
<ItemTemplate>
<asp:Literal ID="HandSetOfferType_id" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"HandSetOfferType.id") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="HandSetOfferType_id" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_id") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="HandSetOfferType_id" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_id") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
<asp:TemplateField Visible="true">
<ItemTemplate>
<asp:Literal ID="HandSetOfferType_cdate" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"HandSetOfferType.cdate") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="HandSetOfferType_cdate" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_cdate") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="HandSetOfferType_cdate" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_cdate") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
<asp:TemplateField Visible="true">
<ItemTemplate>
<asp:Literal ID="HandSetOfferType_cid" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"HandSetOfferType.cid") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="HandSetOfferType_cid" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_cid") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="HandSetOfferType_cid" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_cid") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
<asp:TemplateField Visible="true">
<ItemTemplate>
<asp:Literal ID="HandSetOfferType_did" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"HandSetOfferType.did") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="HandSetOfferType_did" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_did") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="HandSetOfferType_did" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_did") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
<asp:TemplateField Visible="true">
<ItemTemplate>
<asp:Literal ID="HandSetOfferType_expiry_chk" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"HandSetOfferType.expiry_chk") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="HandSetOfferType_expiry_chk" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_expiry_chk") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="HandSetOfferType_expiry_chk" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_expiry_chk") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
<asp:TemplateField Visible="true">
<ItemTemplate>
<asp:Literal ID="HandSetOfferType_active" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"HandSetOfferType.active") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="HandSetOfferType_active" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_active") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="HandSetOfferType_active" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_active") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
<asp:TemplateField Visible="true">
<ItemTemplate>
<asp:Literal ID="HandSetOfferType_name" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"HandSetOfferType.name") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="HandSetOfferType_name" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_name") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="HandSetOfferType_name" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_name") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
<asp:TemplateField Visible="true">
<ItemTemplate>
<asp:Literal ID="HandSetOfferType_edate" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"HandSetOfferType.edate") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="HandSetOfferType_edate" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_edate") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="HandSetOfferType_edate" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_edate") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
<asp:TemplateField Visible="true">
<ItemTemplate>
<asp:Literal ID="HandSetOfferType_ddate" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"HandSetOfferType.ddate") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="HandSetOfferType_ddate" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_ddate") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="HandSetOfferType_ddate" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_ddate") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
<asp:TemplateField Visible="true">
<ItemTemplate>
<asp:Literal ID="HandSetOfferType_sdate" runat="server" Text='<%# DataBinder.Eval(Container.DataItem,"HandSetOfferType.sdate") %>'></asp:Literal>
</ItemTemplate>
<EditItemTemplate>
<asp:TextBox ID="HandSetOfferType_sdate" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_sdate") %>'></asp:TextBox>
</EditItemTemplate>
<InsertItemTemplate>
<asp:TextBox ID="HandSetOfferType_sdate" runat="server" Text='<%# Bind(Container.DataItem,"HandSetOfferType_sdate") %>'></asp:TextBox>
</InsertItemTemplate>
</asp:TemplateField>
</Columns>
</asp:GridView>
<br />

<asp:ObjectDataSource ID="HandSetOfferTypeObj" runat="server" 
 DataObjectTypeName="PCCW.RWL.CORE.HandSetOfferTypeView" TypeName="PCCW.RWL.CORE.HandSetOfferTypeViewDAO"
 DeleteMethod="DeleteHandSetOfferTypeView" InsertMethod="InsertHandSetOfferTypeView"
 SelectMethod="FindALL" UpdateMethod="UpdateHandSetOfferTypeView" OldValuesParameterFormatString="original_{0}" >
 </asp:ObjectDataSource>


    </div>
    </form>
</body>
</html>
